name: altaz
version: 0.0.1
description: >
  This package contains a metric ton of lot of math
  specifcally as it pertains to astronomical calculations.
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
dev_dependencies:
  test: 1.17.8